// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8KSd14V6ray2bLGzs6P4MC0bxb8FqJPw',
    appId: '1:399204907929:web:d39c7df0641196edda3108',
    messagingSenderId: '399204907929',
    projectId: 'digital-tracker-e6ce9',
    authDomain: 'digital-tracker-e6ce9.firebaseapp.com',
    storageBucket: 'digital-tracker-e6ce9.firebasestorage.app',
    measurementId: 'G-K5KG8NWZPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjWUs6FKve6VvjSfl4dQ1OlFYORWK4zLM',
    appId: '1:399204907929:android:f63a7c51492deba1da3108',
    messagingSenderId: '399204907929',
    projectId: 'digital-tracker-e6ce9',
    storageBucket: 'digital-tracker-e6ce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyI8CEsH50RCRvmkMBe6RPV7Ml0RSJlvI',
    appId: '1:399204907929:ios:dbb445470978df55da3108',
    messagingSenderId: '399204907929',
    projectId: 'digital-tracker-e6ce9',
    storageBucket: 'digital-tracker-e6ce9.firebasestorage.app',
    iosBundleId: 'com.example.ptnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyI8CEsH50RCRvmkMBe6RPV7Ml0RSJlvI',
    appId: '1:399204907929:ios:dbb445470978df55da3108',
    messagingSenderId: '399204907929',
    projectId: 'digital-tracker-e6ce9',
    storageBucket: 'digital-tracker-e6ce9.firebasestorage.app',
    iosBundleId: 'com.example.ptnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8KSd14V6ray2bLGzs6P4MC0bxb8FqJPw',
    appId: '1:399204907929:web:f33145bbe55913deda3108',
    messagingSenderId: '399204907929',
    projectId: 'digital-tracker-e6ce9',
    authDomain: 'digital-tracker-e6ce9.firebaseapp.com',
    storageBucket: 'digital-tracker-e6ce9.firebasestorage.app',
    measurementId: 'G-8K4L1L9QCC',
  );
}
